### ISSUE TITLE
Hello Plague

### ISSUE THREAD

**Issue by StellarCS** [OFWModz/PlagueButtonAPI#1]
Yes I have an issue with your code. It's bad. Adding summaries doesn't make your code better... I think you should stop pretending to be a real coder. And get your ego fixed! You are just a nuisance in the modding community on VRChat and that's why no one likes you...

**Comment by OFWModz** [comment]
Is that why even those who hate me use this API as it's so well made? Name me logically something that is actually a flaw.

Summary is there for ease of use, as new people to coding find it extremely useful for learning.

Pretending? I have coded for years, and this is obvious by my repos alone.

Nuisance? I protect people. You're quite the contradiction.
